import { StyleSheet, Dimensions, Platform } from "react-native";
import Constants from "expo-constants";

const { width } = Dimensions.get("window");

const colors = {
  background: "#F7F9FC",
  primary: "#4A6CF7",
  secondary: "#6D7BFF",
  text: "#2C3E50",
  inputBackground: "#FFFFFF",
  border: "#E0E6ED",
  white: "#FFFFFF",
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: Platform.OS === "android" ? Constants.statusBarHeight + 20 : 40,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
    flexGrow: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    marginBottom: 25,
    textAlign: "center",
    color: colors.text,
    letterSpacing: -0.5,
  },
  input: {
    height: 55,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 15,
    backgroundColor: colors.inputBackground,
    color: colors.text,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  expiryDateButton: {
    height: 55,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 15,
    backgroundColor: colors.inputBackground,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  expiryDateButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
  suggestionsContainer: {
    backgroundColor: colors.inputBackground,
    width: "100%",
    borderRadius: 12,
    marginBottom: 15,
    elevation: 5,
    zIndex: 100,
    maxHeight: 150,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  suggestionItemContainer: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  suggestionItem: {
    padding: 12,
    fontSize: 16,
    color: colors.text,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    marginVertical: 10,
    color: colors.text,
    marginLeft: 5,
  },
  picker: {
    backgroundColor: colors.inputBackground,
    color: colors.text,
    marginBottom: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  submitButton: {
    height: 55,
    backgroundColor: colors.primary,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    flexDirection: "row",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  submitButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
    marginRight: 10,
  },
  successOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(74, 108, 247, 0.8)", // Transparent primary color
    justifyContent: "center",
    alignItems: "center",
    zIndex: 200,
  },
  successText: {
    marginTop: 15,
    fontSize: 20,
    color: colors.white,
    fontWeight: "700",
    textAlign: "center",
  },
});

export default styles;
