services:
  postgres:
    image: postgres:latest
    container_name: postgres_wastage
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wastage_db
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
